export interface GrammarExerciseData {
  name: string;
  description: string;
  language: "russian" | "spanish";
  category: string;
  difficulty: number;
  displayOrder: number;
}

export const russianGrammarExercises: GrammarExerciseData[] = [
  {
    name: "Personal Pronouns",
    description: "Learn я, ты, он, она, мы, вы, они",
    language: "russian",
    category: "pronouns",
    difficulty: 1,
    displayOrder: 1,
  },
  {
    name: "Present Tense Conjugations",
    description: "Practice I/You/We/They verb forms",
    language: "russian",
    category: "verbs",
    difficulty: 1,
    displayOrder: 2,
  },
  {
    name: "Noun Gender",
    description: "Identify masculine, feminine, neuter nouns",
    language: "russian",
    category: "nouns",
    difficulty: 1,
    displayOrder: 3,
  },
  {
    name: "Accusative Case",
    description: "Direct objects: see, want, eat, give",
    language: "russian",
    category: "cases",
    difficulty: 2,
    displayOrder: 4,
  },
  {
    name: "Possessive Pronouns",
    description: "Learn мой, твой, его, её, наш, ваш, их",
    language: "russian",
    category: "pronouns",
    difficulty: 1,
    displayOrder: 5,
  },
  {
    name: "Adjective Agreement",
    description: "Match adjectives with noun gender",
    language: "russian",
    category: "adjectives",
    difficulty: 2,
    displayOrder: 6,
  },
  {
    name: "Numbers 1-20",
    description: "Count from один to двадцать",
    language: "russian",
    category: "numbers",
    difficulty: 1,
    displayOrder: 7,
  },
  {
    name: "Colors",
    description: "Learn color words and their forms",
    language: "russian",
    category: "adjectives",
    difficulty: 1,
    displayOrder: 8,
  },
  {
    name: "Family Members",
    description: "Practice мама, папа, брат, сестра",
    language: "russian",
    category: "vocabulary",
    difficulty: 1,
    displayOrder: 9,
  },
  {
    name: "Question Words",
    description: "Learn кто, что, где, когда, почему",
    language: "russian",
    category: "questions",
    difficulty: 1,
    displayOrder: 10,
  },
  {
    name: "Prepositional Case",
    description: "Location: in, on, at places",
    language: "russian",
    category: "cases",
    difficulty: 2,
    displayOrder: 11,
  },
  {
    name: "Past Tense",
    description: "Practice past tense verb endings",
    language: "russian",
    category: "verbs",
    difficulty: 2,
    displayOrder: 12,
  },
  {
    name: "Plural Nouns",
    description: "Form plurals from singular nouns",
    language: "russian",
    category: "nouns",
    difficulty: 2,
    displayOrder: 13,
  },
  {
    name: "Days of the Week",
    description: "Learn понедельник to воскресенье",
    language: "russian",
    category: "vocabulary",
    difficulty: 1,
    displayOrder: 14,
  },
  {
    name: "Common Verbs",
    description: "Practice быть, хотеть, мочь, делать",
    language: "russian",
    category: "verbs",
    difficulty: 1,
    displayOrder: 15,
  },
];

export const spanishGrammarExercises: GrammarExerciseData[] = [
  {
    name: "Personal Pronouns",
    description: "Learn yo, tú, él, ella, nosotros, ellos",
    language: "spanish",
    category: "pronouns",
    difficulty: 1,
    displayOrder: 1,
  },
  {
    name: "Present Tense -AR Verbs",
    description: "Conjugate hablar, cantar, bailar",
    language: "spanish",
    category: "verbs",
    difficulty: 1,
    displayOrder: 2,
  },
  {
    name: "Present Tense -ER/-IR Verbs",
    description: "Conjugate comer, vivir, beber",
    language: "spanish",
    category: "verbs",
    difficulty: 1,
    displayOrder: 3,
  },
  {
    name: "Noun Gender",
    description: "Identify masculine and feminine nouns",
    language: "spanish",
    category: "nouns",
    difficulty: 1,
    displayOrder: 4,
  },
  {
    name: "Definite Articles",
    description: "Practice el, la, los, las",
    language: "spanish",
    category: "articles",
    difficulty: 1,
    displayOrder: 5,
  },
  {
    name: "Indefinite Articles",
    description: "Practice un, una, unos, unas",
    language: "spanish",
    category: "articles",
    difficulty: 1,
    displayOrder: 6,
  },
  {
    name: "Adjective Agreement",
    description: "Match adjectives with noun gender/number",
    language: "spanish",
    category: "adjectives",
    difficulty: 2,
    displayOrder: 7,
  },
  {
    name: "Numbers 1-20",
    description: "Count from uno to veinte",
    language: "spanish",
    category: "numbers",
    difficulty: 1,
    displayOrder: 8,
  },
  {
    name: "Colors",
    description: "Learn color words and their forms",
    language: "spanish",
    category: "adjectives",
    difficulty: 1,
    displayOrder: 9,
  },
  {
    name: "Family Members",
    description: "Practice mamá, papá, hermano, hermana",
    language: "spanish",
    category: "vocabulary",
    difficulty: 1,
    displayOrder: 10,
  },
  {
    name: "Question Words",
    description: "Learn quién, qué, dónde, cuándo, por qué",
    language: "spanish",
    category: "questions",
    difficulty: 1,
    displayOrder: 11,
  },
  {
    name: "Ser vs Estar",
    description: "When to use each verb 'to be'",
    language: "spanish",
    category: "verbs",
    difficulty: 2,
    displayOrder: 12,
  },
  {
    name: "Past Tense (Preterite)",
    description: "Practice simple past verb endings",
    language: "spanish",
    category: "verbs",
    difficulty: 2,
    displayOrder: 13,
  },
  {
    name: "Plural Nouns",
    description: "Form plurals from singular nouns",
    language: "spanish",
    category: "nouns",
    difficulty: 1,
    displayOrder: 14,
  },
  {
    name: "Days of the Week",
    description: "Learn lunes to domingo",
    language: "spanish",
    category: "vocabulary",
    difficulty: 1,
    displayOrder: 15,
  },
];
