export const spanishVocabulary = [
  { spanish: "hola", english: "hello", frequencyRank: 1, category: "greetings" },
  { spanish: "adiós", english: "goodbye", frequencyRank: 2, category: "greetings" },
  { spanish: "gracias", english: "thank you", frequencyRank: 3, category: "greetings" },
  { spanish: "por favor", english: "please", frequencyRank: 4, category: "greetings" },
  { spanish: "sí", english: "yes", frequencyRank: 5, category: "common" },
  { spanish: "no", english: "no", frequencyRank: 6, category: "common" },
  { spanish: "agua", english: "water", frequencyRank: 7, category: "food" },
  { spanish: "pan", english: "bread", frequencyRank: 8, category: "food" },
  { spanish: "leche", english: "milk", frequencyRank: 9, category: "food" },
  { spanish: "manzana", english: "apple", frequencyRank: 10, category: "food" },
  { spanish: "casa", english: "house", frequencyRank: 11, category: "places" },
  { spanish: "escuela", english: "school", frequencyRank: 12, category: "places" },
  { spanish: "libro", english: "book", frequencyRank: 13, category: "objects" },
  { spanish: "perro", english: "dog", frequencyRank: 14, category: "animals" },
  { spanish: "gato", english: "cat", frequencyRank: 15, category: "animals" },
  { spanish: "sol", english: "sun", frequencyRank: 16, category: "nature" },
  { spanish: "luna", english: "moon", frequencyRank: 17, category: "nature" },
  { spanish: "estrella", english: "star", frequencyRank: 18, category: "nature" },
  { spanish: "árbol", english: "tree", frequencyRank: 19, category: "nature" },
  { spanish: "flor", english: "flower", frequencyRank: 20, category: "nature" },
  { spanish: "mamá", english: "mom", frequencyRank: 21, category: "family" },
  { spanish: "papá", english: "dad", frequencyRank: 22, category: "family" },
  { spanish: "hermano", english: "brother", frequencyRank: 23, category: "family" },
  { spanish: "hermana", english: "sister", frequencyRank: 24, category: "family" },
  { spanish: "amigo", english: "friend", frequencyRank: 25, category: "people" },
  { spanish: "niño", english: "boy", frequencyRank: 26, category: "people" },
  { spanish: "niña", english: "girl", frequencyRank: 27, category: "people" },
  { spanish: "uno", english: "one", frequencyRank: 28, category: "numbers" },
  { spanish: "dos", english: "two", frequencyRank: 29, category: "numbers" },
  { spanish: "tres", english: "three", frequencyRank: 30, category: "numbers" },
  { spanish: "cuatro", english: "four", frequencyRank: 31, category: "numbers" },
  { spanish: "cinco", english: "five", frequencyRank: 32, category: "numbers" },
  { spanish: "rojo", english: "red", frequencyRank: 33, category: "colors" },
  { spanish: "azul", english: "blue", frequencyRank: 34, category: "colors" },
  { spanish: "verde", english: "green", frequencyRank: 35, category: "colors" },
  { spanish: "amarillo", english: "yellow", frequencyRank: 36, category: "colors" },
  { spanish: "blanco", english: "white", frequencyRank: 37, category: "colors" },
  { spanish: "negro", english: "black", frequencyRank: 38, category: "colors" },
  { spanish: "grande", english: "big", frequencyRank: 39, category: "adjectives" },
  { spanish: "pequeño", english: "small", frequencyRank: 40, category: "adjectives" },
  { spanish: "bueno", english: "good", frequencyRank: 41, category: "adjectives" },
  { spanish: "malo", english: "bad", frequencyRank: 42, category: "adjectives" },
  { spanish: "feliz", english: "happy", frequencyRank: 43, category: "feelings" },
  { spanish: "triste", english: "sad", frequencyRank: 44, category: "feelings" },
  { spanish: "comer", english: "to eat", frequencyRank: 45, category: "verbs" },
  { spanish: "beber", english: "to drink", frequencyRank: 46, category: "verbs" },
  { spanish: "dormir", english: "to sleep", frequencyRank: 47, category: "verbs" },
  { spanish: "jugar", english: "to play", frequencyRank: 48, category: "verbs" },
  { spanish: "correr", english: "to run", frequencyRank: 49, category: "verbs" },
  { spanish: "caminar", english: "to walk", frequencyRank: 50, category: "verbs" },
  { spanish: "nadar", english: "to swim", frequencyRank: 51, category: "verbs" },
  { spanish: "cantar", english: "to sing", frequencyRank: 52, category: "verbs" },
  { spanish: "bailar", english: "to dance", frequencyRank: 53, category: "verbs" },
  { spanish: "leer", english: "to read", frequencyRank: 54, category: "verbs" },
  { spanish: "escribir", english: "to write", frequencyRank: 55, category: "verbs" },
  { spanish: "mesa", english: "table", frequencyRank: 56, category: "furniture" },
  { spanish: "silla", english: "chair", frequencyRank: 57, category: "furniture" },
  { spanish: "cama", english: "bed", frequencyRank: 58, category: "furniture" },
  { spanish: "puerta", english: "door", frequencyRank: 59, category: "house" },
  { spanish: "ventana", english: "window", frequencyRank: 60, category: "house" },
  { spanish: "cielo", english: "sky", frequencyRank: 61, category: "nature" },
  { spanish: "nube", english: "cloud", frequencyRank: 62, category: "nature" },
  { spanish: "lluvia", english: "rain", frequencyRank: 63, category: "weather" },
  { spanish: "nieve", english: "snow", frequencyRank: 64, category: "weather" },
  { spanish: "viento", english: "wind", frequencyRank: 65, category: "weather" },
  { spanish: "pájaro", english: "bird", frequencyRank: 66, category: "animals" },
  { spanish: "pez", english: "fish", frequencyRank: 67, category: "animals" },
  { spanish: "caballo", english: "horse", frequencyRank: 68, category: "animals" },
  { spanish: "vaca", english: "cow", frequencyRank: 69, category: "animals" },
  { spanish: "cerdo", english: "pig", frequencyRank: 70, category: "animals" },
  { spanish: "pollo", english: "chicken", frequencyRank: 71, category: "animals" },
  { spanish: "huevo", english: "egg", frequencyRank: 72, category: "food" },
  { spanish: "queso", english: "cheese", frequencyRank: 73, category: "food" },
  { spanish: "arroz", english: "rice", frequencyRank: 74, category: "food" },
  { spanish: "carne", english: "meat", frequencyRank: 75, category: "food" },
  { spanish: "fruta", english: "fruit", frequencyRank: 76, category: "food" },
  { spanish: "naranja", english: "orange", frequencyRank: 77, category: "food" },
  { spanish: "plátano", english: "banana", frequencyRank: 78, category: "food" },
  { spanish: "uva", english: "grape", frequencyRank: 79, category: "food" },
  { spanish: "fresa", english: "strawberry", frequencyRank: 80, category: "food" },
  { spanish: "helado", english: "ice cream", frequencyRank: 81, category: "food" },
  { spanish: "pastel", english: "cake", frequencyRank: 82, category: "food" },
  { spanish: "chocolate", english: "chocolate", frequencyRank: 83, category: "food" },
  { spanish: "cuchara", english: "spoon", frequencyRank: 84, category: "kitchen" },
  { spanish: "tenedor", english: "fork", frequencyRank: 85, category: "kitchen" },
  { spanish: "cuchillo", english: "knife", frequencyRank: 86, category: "kitchen" },
  { spanish: "plato", english: "plate", frequencyRank: 87, category: "kitchen" },
  { spanish: "vaso", english: "glass", frequencyRank: 88, category: "kitchen" },
  { spanish: "taza", english: "cup", frequencyRank: 89, category: "kitchen" },
  { spanish: "ojo", english: "eye", frequencyRank: 90, category: "body" },
  { spanish: "nariz", english: "nose", frequencyRank: 91, category: "body" },
  { spanish: "boca", english: "mouth", frequencyRank: 92, category: "body" },
  { spanish: "oreja", english: "ear", frequencyRank: 93, category: "body" },
  { spanish: "mano", english: "hand", frequencyRank: 94, category: "body" },
  { spanish: "pie", english: "foot", frequencyRank: 95, category: "body" },
  { spanish: "cabeza", english: "head", frequencyRank: 96, category: "body" },
  { spanish: "corazón", english: "heart", frequencyRank: 97, category: "body" },
  { spanish: "pelota", english: "ball", frequencyRank: 98, category: "toys" },
  { spanish: "muñeca", english: "doll", frequencyRank: 99, category: "toys" },
  { spanish: "carro", english: "car", frequencyRank: 100, category: "vehicles" },
];
